"""users and agreement header tables

Revision ID: 2ef65b892cde
Revises: 6d351b3144c0
Create Date: 2019-01-03 01:49:57.489883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef65b892cde'
down_revision = '6d351b3144c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fnagrhd',
    sa.Column('comp_id', sa.String(length=10), nullable=False),
    sa.Column('agr_code', sa.String(length=10), nullable=False),
    sa.Column('agr_seq', sa.Integer(), nullable=False),
    sa.Column('userID', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('comp_id', 'agr_code', 'agr_seq')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fnagrhd')
    # ### end Alembic commands ###
