"""empty message

Revision ID: 50fbc7b07345
Revises: 
Create Date: 2018-11-23 01:54:07.127461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fbc7b07345'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('country_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_index(op.f('ix_country_country_code'), 'country', ['country_code'], unique=False)
    op.create_table('users',
    sa.Column('userID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emailID', sa.String(length=100), nullable=False),
    sa.Column('phoneNumber', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=False),
    sa.Column('lastName', sa.String(length=100), nullable=False),
    sa.Column('dateOfBirth', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('is_seller', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.country_id'], ),
    sa.PrimaryKeyConstraint('userID')
    )
    op.create_index(op.f('ix_users_emailID'), 'users', ['emailID'], unique=True)
    op.create_index(op.f('ix_users_phoneNumber'), 'users', ['phoneNumber'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phoneNumber'), table_name='users')
    op.drop_index(op.f('ix_users_emailID'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_country_country_code'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
