"""empty message

Revision ID: 6d351b3144c0
Revises: fa1b9e0b64de
Create Date: 2019-01-03 01:38:30.458518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d351b3144c0'
down_revision = 'fa1b9e0b64de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('emailID', sa.String(length=100), nullable=True),
    sa.Column('passwordHash', sa.String(length=128), nullable=True),
    sa.Column('lastSeen', sa.DateTime(), nullable=True),
    sa.Column('authorized', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('userID')
    )
    op.create_index(op.f('ix_users_emailID'), 'users', ['emailID'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_emailID'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
