"""users and agreement header tables

Revision ID: 9b0579b4e286
Revises: 2ef65b892cde
Create Date: 2019-01-03 01:59:47.346130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0579b4e286'
down_revision = '2ef65b892cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fnagrhd',
    sa.Column('comp_id', sa.String(length=10), nullable=False),
    sa.Column('agr_code', sa.String(length=10), nullable=False),
    sa.Column('agr_seq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('comp_id', 'agr_code', 'agr_seq')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fnagrhd')
    # ### end Alembic commands ###
