"""users and agreement header link

Revision ID: db08a02d0b56
Revises: 9b0579b4e286
Create Date: 2019-01-03 02:01:07.345776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db08a02d0b56'
down_revision = '9b0579b4e286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fnagrhd', sa.Column('userID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fnagrhd', 'users', ['userID'], ['userID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fnagrhd', type_='foreignkey')
    op.drop_column('fnagrhd', 'userID')
    # ### end Alembic commands ###
