"""empty message

Revision ID: fa1b9e0b64de
Revises: 50fbc7b07345
Create Date: 2019-01-03 01:28:32.276401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa1b9e0b64de'
down_revision = '50fbc7b07345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp')
    op.drop_index('ix_country_country_code', table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('country_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('country_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('country_code', mysql.VARCHAR(length=2), nullable=False),
    sa.Column('nationality', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('country_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_country_country_code', 'country', ['country_code'], unique=False)
    op.create_table('temp',
    sa.Column('id', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('data', mysql.VARCHAR(length=100), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
